from app.prompts.analysis_prompt import ANALYSIS_HUMAN_PROMPT, ANALYSIS_SYSTEM_PROMPT
from app.prompts.auction_search_prompt import (
    AUCTION_SEARCH_HUMAN_PROMPT,
    AUCTION_SEARCH_SYSTEM_PROMPT,
)
from app.prompts.market_query_prompt import MARKET_QUERY_HUMAN_PROMPT, MARKET_QUERY_SYSTEM_PROMPT
from app.prompts.market_research_prompt import MARKET_RESEARCH_HUMAN_PROMPT, MARKET_RESEARCH_SYSTEM_PROMPT

__all__ = [
    "ANALYSIS_HUMAN_PROMPT",
    "ANALYSIS_SYSTEM_PROMPT",
    "AUCTION_SEARCH_HUMAN_PROMPT",
    "AUCTION_SEARCH_SYSTEM_PROMPT",
    "MARKET_QUERY_HUMAN_PROMPT",
    "MARKET_QUERY_SYSTEM_PROMPT",
    "MARKET_RESEARCH_HUMAN_PROMPT",
    "MARKET_RESEARCH_SYSTEM_PROMPT",
]
